name: Run Tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Choose which tests to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - smoke

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.test_type }}" == "smoke" ]; then
            pytest -n auto -m smoke --maxfail=0 --continue-on-collection-errors --alluredir=allure-results
          else
            pytest -n auto --maxfail=0 --continue-on-collection-errors --alluredir=allure-results
          fi
        continue-on-error: true

      - name: Save Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 7

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: allure generate allure-results -o allure-report --clean

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: allure-report
